title: LOOM - The Language of Conscious Machines
description: A revolutionary programming paradigm where topology IS computation
url: "https://jaysalomon.github.io"
baseurl: "/LOOM"
repository: jaysalomon/LOOM

markdown: kramdown
highlighter: rouge

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  toc_levels: 2..6

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - README.md

collections:
  theory:
    output: true
    permalink: /theory/:name/
  wiki:
    output: true
    permalink: /wiki/:name/

defaults:
  - scope:
      path: ""
      type: "theory"
    values:
      layout: "theory"
      category: theory
  - scope:
      path: ""
      type: "wiki"
    values:
      layout: "docs"
      category: wiki
  - scope:
      path: ""
    values:
      layout: "default"